### ISSUE TITLE
Issues with Directions as Given

### ISSUE THREAD

**Issue by awlane** [connorkuehl/connorkuehl.github.io#3]
I encountered two problems with the given guide:
1. I would hang at boot without nomodeset specified in GRUB, no matter how far I got in the guide. Did I do something wrong or is this an expected behavior?
2. Is there ANY possible way of making Suspend work without having to be the person who fixes it?

**Comment by connorkuehl** [comment]
1. That's not expected behavior. In fact, `nomodeset` is required for it _not to hang_.
1. Yes, install the Nvidia drivers.
